### ISSUE TITLE
Undesirable characters in generated x-axis label

### ISSUE THREAD

**Issue by Cubesoup** [mathandley/AutoBench#18]
Sometimes (not all the time), little boxes appear before the x-axis label in the generated graph. See:

![InsertTest](https://user-images.githubusercontent.com/521769/68230057-59fef780-ffc6-11e9-8bbd-a0303df5ff01.png)
![ElementTest](https://user-images.githubusercontent.com/521769/68230066-5f5c4200-ffc6-11e9-9b6e-54a3a4e4aa3a.png)

I can stop this from happening by changing the `"\t\t"` in line 104 of AutoBench/Internals/Chart.hs to the empty string, but I'm not sure exactly what I'm doing / why that's the way it is.

**Comment by mathandley** [comment]
Good spot! I'll look into this. The current x-axis label is a hack (https://github.com/mathandley/AutoBench/blob/master/src/AutoBench/Internal/Chart.hs#L97), which I should probably remove if this is happening. When I initially produced graphs using the Chart library, I didn't like the (lack of) space between the x-axis and its label, so I created a label myself and manually positioned it. This must be causing the issue. I will push a fix for it later today.

**Comment by mathandley** [comment]
@Cubesoup, I have just pushed a fix to remove the hack. Please let me know if this fixes your problems with the boxes.

Thanks,
Martin

**Comment by Cubesoup** [comment]
Yup! This seems to have fixed the problem:
![InsertTest](https://user-images.githubusercontent.com/521769/68663212-44c92200-050c-11ea-9088-d48c72c0708e.png)
Thanks!

**Comment by mathandley** [comment]
Great stuff! Many thanks.
